/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICCPeriphery,
  ICCPeripheryInterface,
} from "../../../../../solidity/contracts/bmc/interfaces/ICCPeriphery";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_link",
        type: "string",
      },
    ],
    name: "clearSeq",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_prev",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_seq",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "string",
            name: "src",
            type: "string",
          },
          {
            internalType: "string",
            name: "dst",
            type: "string",
          },
          {
            internalType: "string",
            name: "svc",
            type: "string",
          },
          {
            internalType: "int256",
            name: "sn",
            type: "int256",
          },
          {
            internalType: "bytes",
            name: "message",
            type: "bytes",
          },
          {
            internalType: "int256",
            name: "nsn",
            type: "int256",
          },
          {
            components: [
              {
                internalType: "string",
                name: "network",
                type: "string",
              },
              {
                internalType: "uint256[]",
                name: "values",
                type: "uint256[]",
              },
            ],
            internalType: "struct Types.FeeInfo",
            name: "feeInfo",
            type: "tuple",
          },
        ],
        internalType: "struct Types.BTPMessage",
        name: "_msg",
        type: "tuple",
      },
    ],
    name: "dropMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_sender",
        type: "address",
      },
      {
        internalType: "string",
        name: "_network",
        type: "string",
      },
      {
        internalType: "int256",
        name: "_nsn",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "_result",
        type: "uint256",
      },
    ],
    name: "emitClaimRewardResult",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_next",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "_msg",
        type: "bytes",
      },
    ],
    name: "sendInternal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICCPeriphery__factory {
  static readonly abi = _abi;
  static createInterface(): ICCPeripheryInterface {
    return new utils.Interface(_abi) as ICCPeripheryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICCPeriphery {
    return new Contract(address, _abi, signerOrProvider) as ICCPeriphery;
  }
}
