/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICCService,
  ICCServiceInterface,
} from "../../../../../solidity/contracts/bmc/interfaces/ICCService";

const _abi = [
  {
    inputs: [
      {
        internalType: "int256",
        name: "_nsn",
        type: "int256",
      },
      {
        internalType: "string",
        name: "_dst",
        type: "string",
      },
      {
        internalType: "address",
        name: "_sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "addRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_network",
        type: "string",
      },
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "addReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_network",
        type: "string",
      },
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
    ],
    name: "clearReward",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_rlp",
        type: "bytes",
      },
    ],
    name: "decodeResponseMessage",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "code",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "message",
            type: "string",
          },
        ],
        internalType: "struct Types.ResponseMessage",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_network",
        type: "string",
      },
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
    ],
    name: "getReward",
    outputs: [
      {
        internalType: "uint256",
        name: "_reward",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_network",
        type: "string",
      },
      {
        internalType: "uint256[]",
        name: "_values",
        type: "uint256[]",
      },
    ],
    name: "handleDropFee",
    outputs: [
      {
        components: [
          {
            internalType: "string",
            name: "network",
            type: "string",
          },
          {
            internalType: "uint256[]",
            name: "values",
            type: "uint256[]",
          },
        ],
        internalType: "struct Types.FeeInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_src",
        type: "string",
      },
      {
        internalType: "int256",
        name: "_sn",
        type: "int256",
      },
      {
        components: [
          {
            internalType: "string",
            name: "network",
            type: "string",
          },
          {
            internalType: "uint256[]",
            name: "values",
            type: "uint256[]",
          },
        ],
        internalType: "struct Types.FeeInfo",
        name: "_feeInfo",
        type: "tuple",
      },
    ],
    name: "handleErrorFee",
    outputs: [
      {
        components: [
          {
            internalType: "string",
            name: "network",
            type: "string",
          },
          {
            internalType: "uint256[]",
            name: "values",
            type: "uint256[]",
          },
        ],
        internalType: "struct Types.FeeInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_msg",
        type: "bytes",
      },
    ],
    name: "handleFee",
    outputs: [
      {
        components: [
          {
            internalType: "string",
            name: "src",
            type: "string",
          },
          {
            internalType: "string",
            name: "dst",
            type: "string",
          },
          {
            internalType: "string",
            name: "svc",
            type: "string",
          },
          {
            internalType: "int256",
            name: "sn",
            type: "int256",
          },
          {
            internalType: "bytes",
            name: "message",
            type: "bytes",
          },
          {
            internalType: "int256",
            name: "nsn",
            type: "int256",
          },
          {
            components: [
              {
                internalType: "string",
                name: "network",
                type: "string",
              },
              {
                internalType: "uint256[]",
                name: "values",
                type: "uint256[]",
              },
            ],
            internalType: "struct Types.FeeInfo",
            name: "feeInfo",
            type: "tuple",
          },
        ],
        internalType: "struct Types.BTPMessage",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_to",
        type: "string",
      },
      {
        internalType: "string",
        name: "_svc",
        type: "string",
      },
      {
        internalType: "int256",
        name: "_sn",
        type: "int256",
      },
    ],
    name: "removeResponse",
    outputs: [
      {
        components: [
          {
            internalType: "int256",
            name: "nsn",
            type: "int256",
          },
          {
            components: [
              {
                internalType: "string",
                name: "network",
                type: "string",
              },
              {
                internalType: "uint256[]",
                name: "values",
                type: "uint256[]",
              },
            ],
            internalType: "struct Types.FeeInfo",
            name: "feeInfo",
            type: "tuple",
          },
        ],
        internalType: "struct Types.Response",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICCService__factory {
  static readonly abi = _abi;
  static createInterface(): ICCServiceInterface {
    return new utils.Interface(_abi) as ICCServiceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICCService {
    return new Contract(address, _abi, signerOrProvider) as ICCService;
  }
}
