/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface CallServiceInterface extends utils.Interface {
  functions: {
    "admin()": FunctionFragment;
    "executeCall(uint256,bytes)": FunctionFragment;
    "executeRollback(uint256)": FunctionFragment;
    "getBtpAddress()": FunctionFragment;
    "getFee(string,bool)": FunctionFragment;
    "getProtocolFee()": FunctionFragment;
    "getProtocolFeeHandler()": FunctionFragment;
    "handleBTPError(string,string,uint256,uint256,string)": FunctionFragment;
    "handleBTPMessage(string,string,uint256,bytes)": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "sendCallMessage(string,bytes,bytes)": FunctionFragment;
    "setAdmin(address)": FunctionFragment;
    "setProtocolFee(uint256)": FunctionFragment;
    "setProtocolFeeHandler(address)": FunctionFragment;
    "tryHandleCallMessage(address,string,string,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "admin"
      | "executeCall"
      | "executeRollback"
      | "getBtpAddress"
      | "getFee"
      | "getProtocolFee"
      | "getProtocolFeeHandler"
      | "handleBTPError"
      | "handleBTPMessage"
      | "initialize"
      | "sendCallMessage"
      | "setAdmin"
      | "setProtocolFee"
      | "setProtocolFeeHandler"
      | "tryHandleCallMessage"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executeCall",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "executeRollback",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getBtpAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFee",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "getProtocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProtocolFeeHandler",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "handleBTPError",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "handleBTPMessage",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "sendCallMessage",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFeeHandler",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "tryHandleCallMessage",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeRollback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBtpAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProtocolFeeHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleBTPError",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleBTPMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendCallMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFeeHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tryHandleCallMessage",
    data: BytesLike
  ): Result;

  events: {
    "CallExecuted(uint256,int256,string)": EventFragment;
    "CallMessage(string,string,uint256,uint256,bytes)": EventFragment;
    "CallMessageSent(address,string,uint256,int256)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "ResponseMessage(uint256,int256,string)": EventFragment;
    "RollbackExecuted(uint256,int256,string)": EventFragment;
    "RollbackMessage(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CallExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CallMessage"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CallMessageSent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ResponseMessage"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RollbackExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RollbackMessage"): EventFragment;
}

export interface CallExecutedEventObject {
  _reqId: BigNumber;
  _code: BigNumber;
  _msg: string;
}
export type CallExecutedEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  CallExecutedEventObject
>;

export type CallExecutedEventFilter = TypedEventFilter<CallExecutedEvent>;

export interface CallMessageEventObject {
  _from: string;
  _to: string;
  _sn: BigNumber;
  _reqId: BigNumber;
  _data: string;
}
export type CallMessageEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, string],
  CallMessageEventObject
>;

export type CallMessageEventFilter = TypedEventFilter<CallMessageEvent>;

export interface CallMessageSentEventObject {
  _from: string;
  _to: string;
  _sn: BigNumber;
  _nsn: BigNumber;
}
export type CallMessageSentEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  CallMessageSentEventObject
>;

export type CallMessageSentEventFilter = TypedEventFilter<CallMessageSentEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface ResponseMessageEventObject {
  _sn: BigNumber;
  _code: BigNumber;
  _msg: string;
}
export type ResponseMessageEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  ResponseMessageEventObject
>;

export type ResponseMessageEventFilter = TypedEventFilter<ResponseMessageEvent>;

export interface RollbackExecutedEventObject {
  _sn: BigNumber;
  _code: BigNumber;
  _msg: string;
}
export type RollbackExecutedEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  RollbackExecutedEventObject
>;

export type RollbackExecutedEventFilter =
  TypedEventFilter<RollbackExecutedEvent>;

export interface RollbackMessageEventObject {
  _sn: BigNumber;
}
export type RollbackMessageEvent = TypedEvent<
  [BigNumber],
  RollbackMessageEventObject
>;

export type RollbackMessageEventFilter = TypedEventFilter<RollbackMessageEvent>;

export interface CallService extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CallServiceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    admin(overrides?: CallOverrides): Promise<[string]>;

    executeCall(
      _reqId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    executeRollback(
      _sn: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getBtpAddress(overrides?: CallOverrides): Promise<[string]>;

    getFee(
      _net: PromiseOrValue<string>,
      _rollback: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getProtocolFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    getProtocolFeeHandler(overrides?: CallOverrides): Promise<[string]>;

    handleBTPError(
      _src: PromiseOrValue<string>,
      _svc: PromiseOrValue<string>,
      _sn: PromiseOrValue<BigNumberish>,
      _code: PromiseOrValue<BigNumberish>,
      _msg: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    handleBTPMessage(
      _from: PromiseOrValue<string>,
      _svc: PromiseOrValue<string>,
      _sn: PromiseOrValue<BigNumberish>,
      _msg: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initialize(
      _bmc: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sendCallMessage(
      _to: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      _rollback: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAdmin(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setProtocolFee(
      _value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setProtocolFeeHandler(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    tryHandleCallMessage(
      toAddr: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  admin(overrides?: CallOverrides): Promise<string>;

  executeCall(
    _reqId: PromiseOrValue<BigNumberish>,
    _data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  executeRollback(
    _sn: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getBtpAddress(overrides?: CallOverrides): Promise<string>;

  getFee(
    _net: PromiseOrValue<string>,
    _rollback: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getProtocolFee(overrides?: CallOverrides): Promise<BigNumber>;

  getProtocolFeeHandler(overrides?: CallOverrides): Promise<string>;

  handleBTPError(
    _src: PromiseOrValue<string>,
    _svc: PromiseOrValue<string>,
    _sn: PromiseOrValue<BigNumberish>,
    _code: PromiseOrValue<BigNumberish>,
    _msg: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  handleBTPMessage(
    _from: PromiseOrValue<string>,
    _svc: PromiseOrValue<string>,
    _sn: PromiseOrValue<BigNumberish>,
    _msg: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initialize(
    _bmc: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sendCallMessage(
    _to: PromiseOrValue<string>,
    _data: PromiseOrValue<BytesLike>,
    _rollback: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAdmin(
    _address: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setProtocolFee(
    _value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setProtocolFeeHandler(
    _addr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  tryHandleCallMessage(
    toAddr: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    from: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    admin(overrides?: CallOverrides): Promise<string>;

    executeCall(
      _reqId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    executeRollback(
      _sn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getBtpAddress(overrides?: CallOverrides): Promise<string>;

    getFee(
      _net: PromiseOrValue<string>,
      _rollback: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProtocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    getProtocolFeeHandler(overrides?: CallOverrides): Promise<string>;

    handleBTPError(
      _src: PromiseOrValue<string>,
      _svc: PromiseOrValue<string>,
      _sn: PromiseOrValue<BigNumberish>,
      _code: PromiseOrValue<BigNumberish>,
      _msg: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    handleBTPMessage(
      _from: PromiseOrValue<string>,
      _svc: PromiseOrValue<string>,
      _sn: PromiseOrValue<BigNumberish>,
      _msg: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    initialize(
      _bmc: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    sendCallMessage(
      _to: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      _rollback: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setAdmin(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setProtocolFee(
      _value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setProtocolFeeHandler(
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    tryHandleCallMessage(
      toAddr: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CallExecuted(uint256,int256,string)"(
      _reqId?: PromiseOrValue<BigNumberish> | null,
      _code?: null,
      _msg?: null
    ): CallExecutedEventFilter;
    CallExecuted(
      _reqId?: PromiseOrValue<BigNumberish> | null,
      _code?: null,
      _msg?: null
    ): CallExecutedEventFilter;

    "CallMessage(string,string,uint256,uint256,bytes)"(
      _from?: PromiseOrValue<string> | null,
      _to?: PromiseOrValue<string> | null,
      _sn?: PromiseOrValue<BigNumberish> | null,
      _reqId?: null,
      _data?: null
    ): CallMessageEventFilter;
    CallMessage(
      _from?: PromiseOrValue<string> | null,
      _to?: PromiseOrValue<string> | null,
      _sn?: PromiseOrValue<BigNumberish> | null,
      _reqId?: null,
      _data?: null
    ): CallMessageEventFilter;

    "CallMessageSent(address,string,uint256,int256)"(
      _from?: PromiseOrValue<string> | null,
      _to?: PromiseOrValue<string> | null,
      _sn?: PromiseOrValue<BigNumberish> | null,
      _nsn?: null
    ): CallMessageSentEventFilter;
    CallMessageSent(
      _from?: PromiseOrValue<string> | null,
      _to?: PromiseOrValue<string> | null,
      _sn?: PromiseOrValue<BigNumberish> | null,
      _nsn?: null
    ): CallMessageSentEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "ResponseMessage(uint256,int256,string)"(
      _sn?: PromiseOrValue<BigNumberish> | null,
      _code?: null,
      _msg?: null
    ): ResponseMessageEventFilter;
    ResponseMessage(
      _sn?: PromiseOrValue<BigNumberish> | null,
      _code?: null,
      _msg?: null
    ): ResponseMessageEventFilter;

    "RollbackExecuted(uint256,int256,string)"(
      _sn?: PromiseOrValue<BigNumberish> | null,
      _code?: null,
      _msg?: null
    ): RollbackExecutedEventFilter;
    RollbackExecuted(
      _sn?: PromiseOrValue<BigNumberish> | null,
      _code?: null,
      _msg?: null
    ): RollbackExecutedEventFilter;

    "RollbackMessage(uint256)"(
      _sn?: PromiseOrValue<BigNumberish> | null
    ): RollbackMessageEventFilter;
    RollbackMessage(
      _sn?: PromiseOrValue<BigNumberish> | null
    ): RollbackMessageEventFilter;
  };

  estimateGas: {
    admin(overrides?: CallOverrides): Promise<BigNumber>;

    executeCall(
      _reqId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    executeRollback(
      _sn: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getBtpAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getFee(
      _net: PromiseOrValue<string>,
      _rollback: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProtocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    getProtocolFeeHandler(overrides?: CallOverrides): Promise<BigNumber>;

    handleBTPError(
      _src: PromiseOrValue<string>,
      _svc: PromiseOrValue<string>,
      _sn: PromiseOrValue<BigNumberish>,
      _code: PromiseOrValue<BigNumberish>,
      _msg: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    handleBTPMessage(
      _from: PromiseOrValue<string>,
      _svc: PromiseOrValue<string>,
      _sn: PromiseOrValue<BigNumberish>,
      _msg: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initialize(
      _bmc: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sendCallMessage(
      _to: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      _rollback: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAdmin(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setProtocolFee(
      _value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setProtocolFeeHandler(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    tryHandleCallMessage(
      toAddr: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    executeCall(
      _reqId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    executeRollback(
      _sn: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getBtpAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFee(
      _net: PromiseOrValue<string>,
      _rollback: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProtocolFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getProtocolFeeHandler(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    handleBTPError(
      _src: PromiseOrValue<string>,
      _svc: PromiseOrValue<string>,
      _sn: PromiseOrValue<BigNumberish>,
      _code: PromiseOrValue<BigNumberish>,
      _msg: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    handleBTPMessage(
      _from: PromiseOrValue<string>,
      _svc: PromiseOrValue<string>,
      _sn: PromiseOrValue<BigNumberish>,
      _msg: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      _bmc: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sendCallMessage(
      _to: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      _rollback: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAdmin(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setProtocolFee(
      _value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setProtocolFeeHandler(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    tryHandleCallMessage(
      toAddr: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
