/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICallService__factory } from "./ICallService__factory";
export { ICallServiceReceiver__factory } from "./ICallServiceReceiver__factory";
export { IFeeManage__factory } from "./IFeeManage__factory";
