/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICallService } from "./ICallService";
export type { ICallServiceReceiver } from "./ICallServiceReceiver";
export type { IFeeManage } from "./IFeeManage";
