/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../common";

export interface ErrorsInterface extends utils.Interface {
  functions: {
    "ERR_ALREADY_VERIFIED()": FunctionFragment;
    "ERR_INVALID_ARGS()": FunctionFragment;
    "ERR_NOT_VERIFIABLE()": FunctionFragment;
    "ERR_UNAUTHORIZED()": FunctionFragment;
    "ERR_UNKNOWN()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "ERR_ALREADY_VERIFIED"
      | "ERR_INVALID_ARGS"
      | "ERR_NOT_VERIFIABLE"
      | "ERR_UNAUTHORIZED"
      | "ERR_UNKNOWN"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ERR_ALREADY_VERIFIED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERR_INVALID_ARGS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERR_NOT_VERIFIABLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERR_UNAUTHORIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERR_UNKNOWN",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "ERR_ALREADY_VERIFIED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERR_INVALID_ARGS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERR_NOT_VERIFIABLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERR_UNAUTHORIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERR_UNKNOWN",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Errors extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ErrorsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ERR_ALREADY_VERIFIED(overrides?: CallOverrides): Promise<[string]>;

    ERR_INVALID_ARGS(overrides?: CallOverrides): Promise<[string]>;

    ERR_NOT_VERIFIABLE(overrides?: CallOverrides): Promise<[string]>;

    ERR_UNAUTHORIZED(overrides?: CallOverrides): Promise<[string]>;

    ERR_UNKNOWN(overrides?: CallOverrides): Promise<[string]>;
  };

  ERR_ALREADY_VERIFIED(overrides?: CallOverrides): Promise<string>;

  ERR_INVALID_ARGS(overrides?: CallOverrides): Promise<string>;

  ERR_NOT_VERIFIABLE(overrides?: CallOverrides): Promise<string>;

  ERR_UNAUTHORIZED(overrides?: CallOverrides): Promise<string>;

  ERR_UNKNOWN(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    ERR_ALREADY_VERIFIED(overrides?: CallOverrides): Promise<string>;

    ERR_INVALID_ARGS(overrides?: CallOverrides): Promise<string>;

    ERR_NOT_VERIFIABLE(overrides?: CallOverrides): Promise<string>;

    ERR_UNAUTHORIZED(overrides?: CallOverrides): Promise<string>;

    ERR_UNKNOWN(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    ERR_ALREADY_VERIFIED(overrides?: CallOverrides): Promise<BigNumber>;

    ERR_INVALID_ARGS(overrides?: CallOverrides): Promise<BigNumber>;

    ERR_NOT_VERIFIABLE(overrides?: CallOverrides): Promise<BigNumber>;

    ERR_UNAUTHORIZED(overrides?: CallOverrides): Promise<BigNumber>;

    ERR_UNKNOWN(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ERR_ALREADY_VERIFIED(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ERR_INVALID_ARGS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ERR_NOT_VERIFIABLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ERR_UNAUTHORIZED(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ERR_UNKNOWN(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
