/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export declare namespace IBMV {
  export type VerifierStatusStruct = {
    height: PromiseOrValue<BigNumberish>;
    extra: PromiseOrValue<BytesLike>;
  };

  export type VerifierStatusStructOutput = [BigNumber, string] & {
    height: BigNumber;
    extra: string;
  };
}

export declare namespace Types {
  export type LinkStatusStruct = {
    rxSeq: PromiseOrValue<BigNumberish>;
    txSeq: PromiseOrValue<BigNumberish>;
    verifier: IBMV.VerifierStatusStruct;
    currentHeight: PromiseOrValue<BigNumberish>;
  };

  export type LinkStatusStructOutput = [
    BigNumber,
    BigNumber,
    IBMV.VerifierStatusStructOutput,
    BigNumber
  ] & {
    rxSeq: BigNumber;
    txSeq: BigNumber;
    verifier: IBMV.VerifierStatusStructOutput;
    currentHeight: BigNumber;
  };
}

export interface IBMCPeripheryInterface extends utils.Interface {
  functions: {
    "claimReward(string,string)": FunctionFragment;
    "getBtpAddress()": FunctionFragment;
    "getFee(string,bool)": FunctionFragment;
    "getNetworkAddress()": FunctionFragment;
    "getNetworkSn()": FunctionFragment;
    "getReward(string,address)": FunctionFragment;
    "getStatus(string)": FunctionFragment;
    "handleRelayMessage(string,bytes)": FunctionFragment;
    "sendMessage(string,string,int256,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "claimReward"
      | "getBtpAddress"
      | "getFee"
      | "getNetworkAddress"
      | "getNetworkSn"
      | "getReward"
      | "getStatus"
      | "handleRelayMessage"
      | "sendMessage"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimReward",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getBtpAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFee",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "getNetworkAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNetworkSn",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReward",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatus",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "handleRelayMessage",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessage",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBtpAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNetworkAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNetworkSn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getReward", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "handleRelayMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendMessage",
    data: BytesLike
  ): Result;

  events: {
    "BTPEvent(string,int256,string,string)": EventFragment;
    "ClaimReward(address,string,string,uint256,int256)": EventFragment;
    "ClaimRewardResult(address,string,int256,uint256)": EventFragment;
    "Message(string,uint256,bytes)": EventFragment;
    "MessageDropped(string,uint256,bytes,uint256,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BTPEvent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimReward"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimRewardResult"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Message"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MessageDropped"): EventFragment;
}

export interface BTPEventEventObject {
  _src: string;
  _nsn: BigNumber;
  _next: string;
  _event: string;
}
export type BTPEventEvent = TypedEvent<
  [string, BigNumber, string, string],
  BTPEventEventObject
>;

export type BTPEventEventFilter = TypedEventFilter<BTPEventEvent>;

export interface ClaimRewardEventObject {
  _sender: string;
  _network: string;
  _receiver: string;
  _amount: BigNumber;
  _nsn: BigNumber;
}
export type ClaimRewardEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  ClaimRewardEventObject
>;

export type ClaimRewardEventFilter = TypedEventFilter<ClaimRewardEvent>;

export interface ClaimRewardResultEventObject {
  _sender: string;
  _network: string;
  _nsn: BigNumber;
  _result: BigNumber;
}
export type ClaimRewardResultEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  ClaimRewardResultEventObject
>;

export type ClaimRewardResultEventFilter =
  TypedEventFilter<ClaimRewardResultEvent>;

export interface MessageEventObject {
  _next: string;
  _seq: BigNumber;
  _msg: string;
}
export type MessageEvent = TypedEvent<
  [string, BigNumber, string],
  MessageEventObject
>;

export type MessageEventFilter = TypedEventFilter<MessageEvent>;

export interface MessageDroppedEventObject {
  _prev: string;
  _seq: BigNumber;
  _msg: string;
  _ecode: BigNumber;
  _emsg: string;
}
export type MessageDroppedEvent = TypedEvent<
  [string, BigNumber, string, BigNumber, string],
  MessageDroppedEventObject
>;

export type MessageDroppedEventFilter = TypedEventFilter<MessageDroppedEvent>;

export interface IBMCPeriphery extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IBMCPeripheryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    claimReward(
      _network: PromiseOrValue<string>,
      _receiver: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getBtpAddress(overrides?: CallOverrides): Promise<[string]>;

    getFee(
      _to: PromiseOrValue<string>,
      _response: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _fee: BigNumber }>;

    getNetworkAddress(overrides?: CallOverrides): Promise<[string]>;

    getNetworkSn(overrides?: CallOverrides): Promise<[BigNumber]>;

    getReward(
      _network: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _reward: BigNumber }>;

    getStatus(
      _link: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [Types.LinkStatusStructOutput] & { _status: Types.LinkStatusStructOutput }
    >;

    handleRelayMessage(
      _prev: PromiseOrValue<string>,
      _msg: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sendMessage(
      _to: PromiseOrValue<string>,
      _svc: PromiseOrValue<string>,
      _sn: PromiseOrValue<BigNumberish>,
      _msg: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  claimReward(
    _network: PromiseOrValue<string>,
    _receiver: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getBtpAddress(overrides?: CallOverrides): Promise<string>;

  getFee(
    _to: PromiseOrValue<string>,
    _response: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getNetworkAddress(overrides?: CallOverrides): Promise<string>;

  getNetworkSn(overrides?: CallOverrides): Promise<BigNumber>;

  getReward(
    _network: PromiseOrValue<string>,
    _addr: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getStatus(
    _link: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<Types.LinkStatusStructOutput>;

  handleRelayMessage(
    _prev: PromiseOrValue<string>,
    _msg: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sendMessage(
    _to: PromiseOrValue<string>,
    _svc: PromiseOrValue<string>,
    _sn: PromiseOrValue<BigNumberish>,
    _msg: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    claimReward(
      _network: PromiseOrValue<string>,
      _receiver: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getBtpAddress(overrides?: CallOverrides): Promise<string>;

    getFee(
      _to: PromiseOrValue<string>,
      _response: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNetworkAddress(overrides?: CallOverrides): Promise<string>;

    getNetworkSn(overrides?: CallOverrides): Promise<BigNumber>;

    getReward(
      _network: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStatus(
      _link: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<Types.LinkStatusStructOutput>;

    handleRelayMessage(
      _prev: PromiseOrValue<string>,
      _msg: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    sendMessage(
      _to: PromiseOrValue<string>,
      _svc: PromiseOrValue<string>,
      _sn: PromiseOrValue<BigNumberish>,
      _msg: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "BTPEvent(string,int256,string,string)"(
      _src?: PromiseOrValue<string> | null,
      _nsn?: PromiseOrValue<BigNumberish> | null,
      _next?: null,
      _event?: null
    ): BTPEventEventFilter;
    BTPEvent(
      _src?: PromiseOrValue<string> | null,
      _nsn?: PromiseOrValue<BigNumberish> | null,
      _next?: null,
      _event?: null
    ): BTPEventEventFilter;

    "ClaimReward(address,string,string,uint256,int256)"(
      _sender?: PromiseOrValue<string> | null,
      _network?: PromiseOrValue<string> | null,
      _receiver?: null,
      _amount?: null,
      _nsn?: null
    ): ClaimRewardEventFilter;
    ClaimReward(
      _sender?: PromiseOrValue<string> | null,
      _network?: PromiseOrValue<string> | null,
      _receiver?: null,
      _amount?: null,
      _nsn?: null
    ): ClaimRewardEventFilter;

    "ClaimRewardResult(address,string,int256,uint256)"(
      _sender?: PromiseOrValue<string> | null,
      _network?: PromiseOrValue<string> | null,
      _nsn?: null,
      _result?: null
    ): ClaimRewardResultEventFilter;
    ClaimRewardResult(
      _sender?: PromiseOrValue<string> | null,
      _network?: PromiseOrValue<string> | null,
      _nsn?: null,
      _result?: null
    ): ClaimRewardResultEventFilter;

    "Message(string,uint256,bytes)"(
      _next?: PromiseOrValue<string> | null,
      _seq?: PromiseOrValue<BigNumberish> | null,
      _msg?: null
    ): MessageEventFilter;
    Message(
      _next?: PromiseOrValue<string> | null,
      _seq?: PromiseOrValue<BigNumberish> | null,
      _msg?: null
    ): MessageEventFilter;

    "MessageDropped(string,uint256,bytes,uint256,string)"(
      _prev?: PromiseOrValue<string> | null,
      _seq?: PromiseOrValue<BigNumberish> | null,
      _msg?: null,
      _ecode?: null,
      _emsg?: null
    ): MessageDroppedEventFilter;
    MessageDropped(
      _prev?: PromiseOrValue<string> | null,
      _seq?: PromiseOrValue<BigNumberish> | null,
      _msg?: null,
      _ecode?: null,
      _emsg?: null
    ): MessageDroppedEventFilter;
  };

  estimateGas: {
    claimReward(
      _network: PromiseOrValue<string>,
      _receiver: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getBtpAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getFee(
      _to: PromiseOrValue<string>,
      _response: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNetworkAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getNetworkSn(overrides?: CallOverrides): Promise<BigNumber>;

    getReward(
      _network: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStatus(
      _link: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    handleRelayMessage(
      _prev: PromiseOrValue<string>,
      _msg: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sendMessage(
      _to: PromiseOrValue<string>,
      _svc: PromiseOrValue<string>,
      _sn: PromiseOrValue<BigNumberish>,
      _msg: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claimReward(
      _network: PromiseOrValue<string>,
      _receiver: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getBtpAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFee(
      _to: PromiseOrValue<string>,
      _response: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNetworkAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getNetworkSn(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getReward(
      _network: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStatus(
      _link: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    handleRelayMessage(
      _prev: PromiseOrValue<string>,
      _msg: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sendMessage(
      _to: PromiseOrValue<string>,
      _svc: PromiseOrValue<string>,
      _sn: PromiseOrValue<BigNumberish>,
      _msg: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
