/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export declare namespace Types {
  export type RouteStruct = {
    dst: PromiseOrValue<string>;
    next: PromiseOrValue<string>;
  };

  export type RouteStructOutput = [string, string] & {
    dst: string;
    next: string;
  };

  export type ServiceStruct = {
    svc: PromiseOrValue<string>;
    addr: PromiseOrValue<string>;
  };

  export type ServiceStructOutput = [string, string] & {
    svc: string;
    addr: string;
  };

  export type VerifierStruct = {
    net: PromiseOrValue<string>;
    addr: PromiseOrValue<string>;
  };

  export type VerifierStructOutput = [string, string] & {
    net: string;
    addr: string;
  };
}

export interface IBMCManagementInterface extends utils.Interface {
  functions: {
    "addLink(string)": FunctionFragment;
    "addRelay(string,address)": FunctionFragment;
    "addRoute(string,string)": FunctionFragment;
    "addService(string,address)": FunctionFragment;
    "addVerifier(string,address)": FunctionFragment;
    "dropMessage(string,uint256,string,int256,int256,string,uint256[])": FunctionFragment;
    "getFeeHandler()": FunctionFragment;
    "getFeeTable(string[])": FunctionFragment;
    "getLinks()": FunctionFragment;
    "getRelays(string)": FunctionFragment;
    "getRoutes()": FunctionFragment;
    "getServices()": FunctionFragment;
    "getVerifiers()": FunctionFragment;
    "removeLink(string)": FunctionFragment;
    "removeRelay(string,address)": FunctionFragment;
    "removeRoute(string)": FunctionFragment;
    "removeService(string)": FunctionFragment;
    "removeVerifier(string)": FunctionFragment;
    "setFeeHandler(address)": FunctionFragment;
    "setFeeTable(string[],uint256[][])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addLink"
      | "addRelay"
      | "addRoute"
      | "addService"
      | "addVerifier"
      | "dropMessage"
      | "getFeeHandler"
      | "getFeeTable"
      | "getLinks"
      | "getRelays"
      | "getRoutes"
      | "getServices"
      | "getVerifiers"
      | "removeLink"
      | "removeRelay"
      | "removeRoute"
      | "removeService"
      | "removeVerifier"
      | "setFeeHandler"
      | "setFeeTable"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addLink",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addRelay",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addRoute",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addService",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addVerifier",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "dropMessage",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeHandler",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeTable",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(functionFragment: "getLinks", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getRelays",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "getRoutes", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getServices",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifiers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeLink",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeRelay",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeRoute",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeService",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeVerifier",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeHandler",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeTable",
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>[][]]
  ): string;

  decodeFunctionResult(functionFragment: "addLink", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addRelay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addRoute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addService", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dropMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeTable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLinks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRelays", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRoutes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getServices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "removeLink", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeRelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeRoute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeTable",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IBMCManagement extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IBMCManagementInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addLink(
      _link: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addRelay(
      _link: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addRoute(
      _dst: PromiseOrValue<string>,
      _link: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addService(
      _svc: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addVerifier(
      _net: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    dropMessage(
      _src: PromiseOrValue<string>,
      _seq: PromiseOrValue<BigNumberish>,
      _svc: PromiseOrValue<string>,
      _sn: PromiseOrValue<BigNumberish>,
      _nsn: PromiseOrValue<BigNumberish>,
      _feeNetwork: PromiseOrValue<string>,
      _feeValues: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getFeeHandler(
      overrides?: CallOverrides
    ): Promise<[string] & { _addr: string }>;

    getFeeTable(
      _dst: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[][]] & { _feeTable: BigNumber[][] }>;

    getLinks(
      overrides?: CallOverrides
    ): Promise<[string[]] & { _links: string[] }>;

    getRelays(
      _link: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]] & { _relays: string[] }>;

    getRoutes(
      overrides?: CallOverrides
    ): Promise<
      [Types.RouteStructOutput[]] & { _routes: Types.RouteStructOutput[] }
    >;

    getServices(
      overrides?: CallOverrides
    ): Promise<
      [Types.ServiceStructOutput[]] & {
        _servicers: Types.ServiceStructOutput[];
      }
    >;

    getVerifiers(
      overrides?: CallOverrides
    ): Promise<
      [Types.VerifierStructOutput[]] & {
        _verifiers: Types.VerifierStructOutput[];
      }
    >;

    removeLink(
      _link: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeRelay(
      _link: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeRoute(
      _dst: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeService(
      _svc: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeVerifier(
      _net: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFeeHandler(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFeeTable(
      _dst: PromiseOrValue<string>[],
      _value: PromiseOrValue<BigNumberish>[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addLink(
    _link: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addRelay(
    _link: PromiseOrValue<string>,
    _addr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addRoute(
    _dst: PromiseOrValue<string>,
    _link: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addService(
    _svc: PromiseOrValue<string>,
    _addr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addVerifier(
    _net: PromiseOrValue<string>,
    _addr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  dropMessage(
    _src: PromiseOrValue<string>,
    _seq: PromiseOrValue<BigNumberish>,
    _svc: PromiseOrValue<string>,
    _sn: PromiseOrValue<BigNumberish>,
    _nsn: PromiseOrValue<BigNumberish>,
    _feeNetwork: PromiseOrValue<string>,
    _feeValues: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getFeeHandler(overrides?: CallOverrides): Promise<string>;

  getFeeTable(
    _dst: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<BigNumber[][]>;

  getLinks(overrides?: CallOverrides): Promise<string[]>;

  getRelays(
    _link: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getRoutes(overrides?: CallOverrides): Promise<Types.RouteStructOutput[]>;

  getServices(overrides?: CallOverrides): Promise<Types.ServiceStructOutput[]>;

  getVerifiers(
    overrides?: CallOverrides
  ): Promise<Types.VerifierStructOutput[]>;

  removeLink(
    _link: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeRelay(
    _link: PromiseOrValue<string>,
    _addr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeRoute(
    _dst: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeService(
    _svc: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeVerifier(
    _net: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFeeHandler(
    _addr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFeeTable(
    _dst: PromiseOrValue<string>[],
    _value: PromiseOrValue<BigNumberish>[][],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addLink(
      _link: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addRelay(
      _link: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addRoute(
      _dst: PromiseOrValue<string>,
      _link: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addService(
      _svc: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addVerifier(
      _net: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    dropMessage(
      _src: PromiseOrValue<string>,
      _seq: PromiseOrValue<BigNumberish>,
      _svc: PromiseOrValue<string>,
      _sn: PromiseOrValue<BigNumberish>,
      _nsn: PromiseOrValue<BigNumberish>,
      _feeNetwork: PromiseOrValue<string>,
      _feeValues: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    getFeeHandler(overrides?: CallOverrides): Promise<string>;

    getFeeTable(
      _dst: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber[][]>;

    getLinks(overrides?: CallOverrides): Promise<string[]>;

    getRelays(
      _link: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getRoutes(overrides?: CallOverrides): Promise<Types.RouteStructOutput[]>;

    getServices(
      overrides?: CallOverrides
    ): Promise<Types.ServiceStructOutput[]>;

    getVerifiers(
      overrides?: CallOverrides
    ): Promise<Types.VerifierStructOutput[]>;

    removeLink(
      _link: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeRelay(
      _link: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeRoute(
      _dst: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeService(
      _svc: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeVerifier(
      _net: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFeeHandler(
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFeeTable(
      _dst: PromiseOrValue<string>[],
      _value: PromiseOrValue<BigNumberish>[][],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addLink(
      _link: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addRelay(
      _link: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addRoute(
      _dst: PromiseOrValue<string>,
      _link: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addService(
      _svc: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addVerifier(
      _net: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    dropMessage(
      _src: PromiseOrValue<string>,
      _seq: PromiseOrValue<BigNumberish>,
      _svc: PromiseOrValue<string>,
      _sn: PromiseOrValue<BigNumberish>,
      _nsn: PromiseOrValue<BigNumberish>,
      _feeNetwork: PromiseOrValue<string>,
      _feeValues: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getFeeHandler(overrides?: CallOverrides): Promise<BigNumber>;

    getFeeTable(
      _dst: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLinks(overrides?: CallOverrides): Promise<BigNumber>;

    getRelays(
      _link: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoutes(overrides?: CallOverrides): Promise<BigNumber>;

    getServices(overrides?: CallOverrides): Promise<BigNumber>;

    getVerifiers(overrides?: CallOverrides): Promise<BigNumber>;

    removeLink(
      _link: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeRelay(
      _link: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeRoute(
      _dst: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeService(
      _svc: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeVerifier(
      _net: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFeeHandler(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFeeTable(
      _dst: PromiseOrValue<string>[],
      _value: PromiseOrValue<BigNumberish>[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addLink(
      _link: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addRelay(
      _link: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addRoute(
      _dst: PromiseOrValue<string>,
      _link: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addService(
      _svc: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addVerifier(
      _net: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    dropMessage(
      _src: PromiseOrValue<string>,
      _seq: PromiseOrValue<BigNumberish>,
      _svc: PromiseOrValue<string>,
      _sn: PromiseOrValue<BigNumberish>,
      _nsn: PromiseOrValue<BigNumberish>,
      _feeNetwork: PromiseOrValue<string>,
      _feeValues: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getFeeHandler(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFeeTable(
      _dst: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLinks(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRelays(
      _link: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoutes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getServices(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getVerifiers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeLink(
      _link: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeRelay(
      _link: PromiseOrValue<string>,
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeRoute(
      _dst: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeService(
      _svc: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeVerifier(
      _net: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFeeHandler(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFeeTable(
      _dst: PromiseOrValue<string>[],
      _value: PromiseOrValue<BigNumberish>[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
