/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBMCManagement } from "./IBMCManagement";
export type { IBMCPeriphery } from "./IBMCPeriphery";
export type { ICCManagement } from "./ICCManagement";
export type { ICCPeriphery } from "./ICCPeriphery";
export type { ICCService } from "./ICCService";
export type { IOwnerManager } from "./IOwnerManager";
