/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBMV,
  IBMVInterface,
} from "../../../../../@iconfoundation/btp2-solidity-library/contracts/interfaces/IBMV";

const _abi = [
  {
    inputs: [],
    name: "getStatus",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "height",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "extra",
            type: "bytes",
          },
        ],
        internalType: "struct IBMV.VerifierStatus",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_bmc",
        type: "string",
      },
      {
        internalType: "string",
        name: "_prev",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_seq",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_msg",
        type: "bytes",
      },
    ],
    name: "handleRelayMessage",
    outputs: [
      {
        internalType: "bytes[]",
        name: "",
        type: "bytes[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBMV__factory {
  static readonly abi = _abi;
  static createInterface(): IBMVInterface {
    return new utils.Interface(_abi) as IBMVInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IBMV {
    return new Contract(address, _abi, signerOrProvider) as IBMV;
  }
}
