name: Code Coverage with Codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21.4"

      - name: GO test
        run: |
          go list -f '{{.Dir}}/...' -m | grep -v '/test/functional/' |xargs go test -short -timeout=3m -covermode=atomic -coverprofile=coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
