name: Snapshot

on:
  workflow_dispatch:
    inputs:
      kurtosis_version:
        description: "kurtosis_version"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.4"

      - name: Install Goreleaser
        run: |
          go install github.com/goreleaser/goreleaser@latest

      - name: Run Goreleaser
        env:
          KURT_CLI_VERSION: ${{ github.event.inputs.kurtosis_version }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          cd cli/ && goreleaser release --rm-dist --clean
