name: goreleaser

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches-ignore:
      - main

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          tag: ${{ env.GITHUB_REF_NAME }}
          args: release --snapshot --clean  --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
