name: Smoke Test

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:

jobs:
  smoke_test:
    if: ${{ github.event.label.name == 'test:smoke' }}
    name: Smoke Testing
    runs-on: "ubuntu-latest"
    env:
      DIVE_BINARY_PATH: ${{ github.workspace }}/dive

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          check-latest: true

      - name: Installing Kurtosis CLI and starting the kurtosis engine
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
          kurtosis engine start

      - name: Running eth chain command tests
        run: |
             cd test && make run-smoke
