name: DIVE CLI

on:
  push:
    branches:
      - CKIP-120-Create-github-action-for-smoke-test

jobs:
  test:
    name: Smoke Testing
    runs-on: "ubuntu-latest"
    env:
        DIVE_BINARY_PATH: ${{ github.workspace }}/dive

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.20.1
        
        - name: Installing Kurtosis CLI and starting the kurtosis engine
          run: |
            echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
            sudo apt update
            sudo apt install kurtosis-cli
            kurtosis engine start
        
        - name: Building DIVE binary with latest changes
          run: |
            cd cli && go mod tidy
            go build -o $DIVE_BINARY_PATH

        - name: Test bridge between icon and eth
          run: |
            $DIVE_BINARY_PATH bridge btp --chainA icon --chainB eth
        
        - name: Test bridge between icon and hardhat with icon bridge set to true
          run: |
            $DIVE_BINARY_PATH clean
            $DIVE_BINARY_PATH bridge btp --chainA icon --chainB eth --bridge

        - name: Test bridge between icon and icon
          run: |
            $DIVE_BINARY_PATH clean
            $DIVE_BINARY_PATH bridge btp --chainA icon --chainB icon
          
        

